version: '3.7'

services:

  estoques_db:
    image: postgres
    container_name: estoques_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=estoques
      - POSTGRES_PASSWORD=estoques
      - POSTGRES_DB=estoques_db
    volumes:
      - estoques_db_data:/var/lib/postgresql/data
    restart: always

## Default Volume Settings
volumes:
  estoques_db_data: {}